import type { Metadata } from "next";
import "./globals.css";

import { Nunito } from "next/font/google";

const nunito = Nunito({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Bethany Recording Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className={nunito.className}>
        {children}
      </body>
    </html>
  );
}
